CREATE DATABASE OLA;
USE OLA;

-- TO SHOW THE DATA
SELECT * FROM OLA_BOOKING; 

-- TOTAL NUMBER OF BOOKING
SELECT COUNT(*) AS TOTAL_BOOKING FROM OLA_BOOKING; 

-- TOTAL REVENUE
SELECT SUM(RIDE_FARE) AS TOTAL_REVENUE FROM OLA_BOOKING
WHERE BOOKING_STATUS="COMPLETED";

-- BOOKING STATUS ANALYSIS
SELECT BOOKING_STATUS,COUNT(*) AS TOTAL
FROM OLA_BOOKING
GROUP BY BOOKING_STATUS;

-- VEHICLE TYPE PERFORMANCE
SELECT VEHICLE_TYPE,COUNT(*) AS TOTAL_RIDES
FROM OLA_BOOKING
GROUP BY VEHICLE_TYPE
ORDER BY TOTAL_RIDES DESC;

-- HIGHEST REVENUE LOCATIONS
SELECT PICKUP_LOCATION,
SUM(RIDE_FARE) AS REVENUE
FROM OLA_BOOKING
GROUP BY PICKUP_LOCATION
ORDER BY REVENUE DESC;

-- AVG RIDE DISTANCE
SELECT AVG(RIDE_DISTANCE_KM) AS AVG_DIST 
FROM OLA_BOOKING;

-- CUSTOMERS CANCELLATION REASONS
SELECT REASON_FOR_CANCELLING_BY_CUSTOMER,
COUNT(*) AS TOTAL
FROM OLA_BOOKING
GROUP BY REASON_FOR_CANCELLING_BY_CUSTOMER
ORDER BY TOTAL DESC;

SELECT DRIVER_CANCEL_REASON,
COUNT(*) AS TOTAL
FROM OLA_BOOKING
GROUP BY DRIVER_CANCEL_REASON;

-- PAYMENT METHOD ANALYSIS
SELECT PAYMENT_METHOD,
COUNT(*) AS TOTAL_TRANSACTION
FROM OLA_BOOKING
GROUP BY PAYMENT_METHOD;

-- PEAK BOOKING DAYS
SELECT DISTINCT(DATE) AS DAY_NAME,
COUNT(*) AS TOTAL_RIDES
FROM OLA_BOOKING
GROUP BY DAY_NAME
ORDER BY TOTAL_RIDES DESC;

-- MONTHELY REVENUE
SELECT MONTHNAME(DATE) AS MONTH_NAME,
SUM(RIDE_FARE) AS REVENUE
FROM OLA_BOOKING
GROUP BY MONTH_NAME;

-- CREATE KPI QUERIES FOR POWER bi
SELECT(COUNT(CASE WHEN BOOKING_STATUS != 'COMPLETED' 
THEN 1 END)*1000.0)
/COUNT(*) AS CANCELLATION_RATE
FROM OLA_BOOKING;

-- RETRIEVE ALL COMPLETED BOOKING
SELECT * FROM OLA_BOOKING
WHERE BOOKING_STATUS='COMPLETED';

-- AVG RIDE DISTANCE FOR EACH VECHICLE TYPE
SELECT VEHICLE_TYPE, 
AVG(RIDE_DISTANCE_KM) AS RIDE_DISTANCE
FROM OLA_BOOKING
GROUP BY VEHICLE_TYPE;

-- TOTAL NUMBER OF RIDE CANCELLED BY CUSTOMER 
SELECT COUNT(*) FROM OLA_BOOKING
WHERE BOOKING_STATUS='CANCELLED_RIDE_BY_CUSTOMER'; 

-- TOP 5 CUSTOMER WHO BOOKED THE HIGHEST NO OF RIDES
SELECT CUSTOMER_ID,COUNT(BOOKING_ID) AS TOTAL_RIDE 
FROM OLA_BOOKING
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_RIDE DESC
LIMIT 5;

-- NO OF RIDE CANCELLED DRIVER DUE TO PERSIONEL AND CAR ISSUES
SELECT COUNT(*) FROM OLA_BOOKING
WHERE CANCELLED_RIDES_BY_DRIVER='PERSONAL AND CAR RELATED ISSUE';

-- MAX AND MIN DRIVER RATING FOR SEDAN BOOKING
SELECT MAX(DRIVER_RATINGS) AS MAX_RATING,
MIN(DRIVER_RATINGS) AS MIN_RATINGS 
FROM OLA_BOOKING
WHERE VEHICLE_TYPE='PRIME SEDAN';  -- IN MYBDATA THERE IS NO DRIVER RATINGS



